#!/usr/bin/env python3
"""Aggregates a pitch census run into the markdown tables embedded in
docs/research/pitch-accent-shapes.md.

Every table is keyed by dictionary, because the questions this census exists to
answer are per-dictionary ones: which archive carries the marks, which archive
disagrees with the others, and how wide the widest reading gets.
"""

from __future__ import annotations

import argparse
import collections
import json
from pathlib import Path

DEFAULT_IN = Path(__file__).parent / "results" / "census.json"
DEFAULT_OUT = Path(__file__).parent / "results" / "tables.md"


def n(value: int) -> str:
    """Thin-spaced thousands, the spelling the other research docs use."""
    return f"{value:,}".replace(",", " ")


def pct(part: int, whole: int) -> str:
    return "-" if not whole else f"{100 * part / whole:.1f}%"


def table(header: list[str], rows: list[list[str]]) -> list[str]:
    align = ["---"] + ["---:"] * (len(header) - 1)
    return [
        "| " + " | ".join(header) + " |",
        "|" + "|".join(align) + "|",
        *("| " + " | ".join(r) + " |" for r in rows),
        "",
    ]


def pitch_dictionaries(census: dict) -> list[dict]:
    return sorted(
        (d for d in census["dictionaries"] if d["pitch_rows"]),
        key=lambda d: -d["pitch_rows"],
    )


def totals(dicts: list[dict], field: str) -> int:
    return sum(d[field] for d in dicts)


def merged(dicts: list[dict], field: str) -> collections.Counter:
    out: collections.Counter = collections.Counter()
    for d in dicts:
        out.update({int(k) if k.lstrip("-").isdigit() else k: v
                    for k, v in d[field].items()})
    return out


def render(census: dict) -> str:
    P = pitch_dictionaries(census)
    every = census["dictionaries"]
    out: list[str] = [f"<!-- generated by tools/pitch-census/report.py from {census['corpus']} -->", ""]

    out += ["## Which archives carry pitch", ""]
    out += table(
        ["archive", "title", "revision", "meta banks", "meta rows", "modes seen",
         "CRC-bad members"],
        [
            [d["file"], str(d["title"]), str(d["revision"]), n(d["banks"]),
             n(d["rows"]),
             ", ".join(f"{k} {n(v)}" for k, v in sorted(d["modes"].items())) or "-",
             n(len(d["crc_mismatch"]))]
            for d in sorted(every, key=lambda d: (-d["pitch_rows"], -d["rows"]))
            if d["rows"] or d["error"] or "Pitch" in d["file"]
        ],
    )
    modes = collections.Counter()
    for d in every:
        modes.update(d["modes"])
    out += [
        f"Over all {n(len(every))} archives: "
        + ", ".join(f"`{k}` {n(v)} rows" for k, v in sorted(modes.items()))
        + f". Archives with a nested `term_meta_bank_`: "
        + n(sum(1 for d in every if d["banks_nested"])) + ".",
        "",
    ]

    out += ["## Pitch rows per dictionary", ""]
    out += table(
        ["dictionary", "rows", "expressions", "readings", "expr+reading pairs",
         "pairs over 2+ rows", "rows with 2+ accents", "accents", "max accents/row",
         "max morae", "max position"],
        [
            [str(d["title"]), n(d["pitch_rows"]), n(d["expressions"]),
             n(d["readings"]), n(d["pairs"]), n(d["pairs_multi_row"]),
             n(d["rows_multi_accent"]), n(d["accents"]),
             str(d["max_accents_per_row"]), str(d["max_morae"]),
             str(d["max_position"])]
            for d in P
        ] + [[
            "**total**", n(totals(P, "pitch_rows")), n(totals(P, "expressions")),
            n(totals(P, "readings")), n(totals(P, "pairs")),
            n(totals(P, "pairs_multi_row")), n(totals(P, "rows_multi_accent")),
            n(totals(P, "accents")), str(max(d["max_accents_per_row"] for d in P)),
            str(max(d["max_morae"] for d in P)),
            str(max(d["max_position"] for d in P)),
        ]],
    )

    out += ["## Optional fields", ""]
    out += table(
        ["dictionary", "accents", "`nasal` present", "`nasal` non-empty",
         "`devoice` present", "`devoice` non-empty", "`tags`", "`position` forms"],
        [
            [str(d["title"]), n(d["accents"]),
             pct(d["accent_fields"].get("nasal", 0), d["accents"]),
             f'{n(d["accent_fields"].get("nasal (non-empty)", 0))} '
             f'({pct(d["accent_fields"].get("nasal (non-empty)", 0), d["accents"])})',
             pct(d["accent_fields"].get("devoice", 0), d["accents"]),
             f'{n(d["accent_fields"].get("devoice (non-empty)", 0))} '
             f'({pct(d["accent_fields"].get("devoice (non-empty)", 0), d["accents"])})',
             n(d["accent_fields"].get("tags", 0)),
             ", ".join(f"{k} {n(v)}" for k, v in sorted(d["position_forms"].items()))]
            for d in P
        ],
    )
    accents = totals(P, "accents")
    marks = merged(P, "accent_fields")
    out += [
        f'Across all {n(accents)} accents: `nasal` non-empty on '
        f'{n(marks["nasal (non-empty)"])} ({pct(marks["nasal (non-empty)"], accents)}), '
        f'`devoice` non-empty on {n(marks["devoice (non-empty)"])} '
        f'({pct(marks["devoice (non-empty)"], accents)}). Rows carrying either: '
        f'{n(merged(P, "rows_with_field")["nasal or devoice (non-empty)"])} of '
        f'{n(totals(P, "pitch_rows"))} '
        f'({pct(merged(P, "rows_with_field")["nasal or devoice (non-empty)"], totals(P, "pitch_rows"))}).',
        "",
    ]

    out += ["## Downstep distribution", ""]
    pos = merged(P, "position_values")
    total_pos = sum(pos.values())
    out += table(
        ["`position`", "accents", "share"],
        [[str(k), n(pos[k]), pct(pos[k], total_pos)] for k in sorted(pos)],
    )

    out += ["## Mora count of the reading", ""]
    mora = merged(P, "mora_histogram")
    total_mora = sum(mora.values())
    out += table(
        ["morae", "rows", "share"],
        [[str(k), n(mora[k]), pct(mora[k], total_mora)] for k in sorted(mora)],
    )

    out += ["## Accents per row, and per pair after merging rows", ""]
    per_row = merged(P, "accents_histogram")
    out += table(
        ["accents in one row", "rows"],
        [[str(k), n(per_row[k])] for k in sorted(per_row)],
    )
    out += table(
        ["dictionary", "distinct accents per pair", "widest pair"],
        [
            [str(d["title"]),
             ", ".join(f"{k}: {n(v)}" for k, v in sorted(
                 d["distinct_accents_histogram"].items(), key=lambda kv: int(kv[0]))),
             f'{d["max_distinct_accents_per_pair"]} ({d["max_distinct_accents_pair"]})']
            for d in P
        ],
    )

    for label, key in (("position only", "agreement"),
                       ("position plus nasal and devoice", "agreement_with_marks")):
        a = census[key]
        out += [f"## Cross-dictionary agreement, {label}", ""]
        known = sum(v for k, v in a["totals"].items() if k != "one dictionary only")
        out += table(
            ["outcome", "expr+reading pairs", "share of pairs 2+ dictionaries know"],
            [[k, n(v), "-" if k == "one dictionary only" else pct(v, known)]
             for k, v in sorted(a["totals"].items(), key=lambda kv: -kv[1])],
        )
        out += [
            f'{n(a["keys"])} distinct expression+reading pairs; {n(known)} known to two '
            f'or more dictionaries. Over those, {n(a["claims_multi_dictionary"])} accent '
            f'claims arrive and {n(a["distinct_multi_dictionary"])} survive '
            f'deduplication ('
            f'{pct(a["claims_multi_dictionary"] - a["distinct_multi_dictionary"], a["claims_multi_dictionary"])}'
            " collapse). Widest pair after union: "
            f'{a["max_accents_after_union"]} accents.',
            "",
        ]
        out += table(
            ["pair", "shared pairs", "identical", "differing", "differing share"],
            [[k, n(v["shared"]), n(v["identical"]), n(v["differing"]),
              pct(v["differing"], v["shared"])]
             for k, v in a["pairwise"].items()],
        )
        out += table(
            ["accents after union", "pairs"],
            [[k, n(v)] for k, v in a["union_histogram"].items()],
        )

    out += ["## Readings that are not plain kana", ""]
    out += table(
        ["dictionary", "rows", "characters"],
        [[str(d["title"]), n(d["reading_not_kana"]),
          ", ".join(f"`{c}` {n(v)}" for c, v in sorted(d["reading_odd_chars"].items()))
          or "-"]
         for d in P],
    )

    out += ["## Record rows and fixtures", ""]
    for d in P:
        out += [f"### {d['title']}", ""]
        for name, row in sorted(d["records"].items()):
            out += [f"- {name}:", "", "```json", row, "```", ""]
        for name, rows in sorted(d["fixtures"].items()):
            out += [f"- {name}:", "", "```json", *rows, "```", ""]

    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--in", dest="src", type=Path, default=DEFAULT_IN)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()

    census = json.loads(args.src.read_text(encoding="utf-8"))
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(census), encoding="utf-8")
    print(f"{args.src} -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
